import { faCircleXmark, faUser, IconDefinition } from "@fortawesome/free-regular-svg-icons";
import {
	faBackwardStep,
	faBook,
	faChevronLeft,
	faChevronRight,
	faCircleNotch,
	faCirclePause,
	faCirclePlay,
	faForwardStep,
	faHome,
	faPlus,
	faSearch,
	faVolumeHigh,
	faVolumeLow,
	faVolumeMute,
} from "@fortawesome/free-solid-svg-icons";

export const fontAwesomeIcons: IconDefinition[] = [
	faCirclePlay,
	faHome,
	faSearch,
	faBook,
	faPlus,
	faChevronLeft,
	faChevronRight,
	faUser,
	faCircleNotch,
	faCircleXmark,
	faBackwardStep,
	faForwardStep,
	faCirclePause,
	faVolumeMute,
	faVolumeLow,
	faVolumeHigh,
];
